### ISSUE TITLE
Cannot find module ....../dist/query imported from ......./dist/index.js

### ISSUE THREAD

**Issue by max-programming** [react-appwrite/react-appwrite#42]
So this is my code
```tsx
import { useOAuth2SignIn } from 'react-appwrite';

export default function Signup() {
  const signIn = useOAuth2SignIn();

  function loginWithGoogle() {
    signIn.mutate({
      provider: 'google',
      successUrl: 'http://localhost:3000/',
      failureUrl: 'http://localhost:3000/signup',
    });
    // account.createOAuth2Session(
    //   'google',
    //   'http://localhost:3000/',
    //   'http://localhost:3000/login'
    // );
  }

  return (
    <div>
      <h1>Sign up</h1>
      <button onClick={loginWithGoogle}>Login with google</button>
    </div>
  );
}
```

And this is the error I get
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'E:\Projects\selfchat\node_modules\react-appwrite\dist\query' imported from E:\Projects\selfchat\node_modules\react-appwrite\dist\index.js
```

I tried installing react query manually thinking that would solve the problem but it didn't

**Comment by sanny-io** [comment]
What version of the appwrite package and react-appwrite package are you using?

**Comment by HayHay404** [comment]
I'm having the same issue. I'm using appwrite 11, react-query 4.24.9, with react-appwrite 0.4.1. I tried reinstalling the package and manually installed react-query. Also tried downgrading from next@13.4.1 to 13.1.6 (like the example). 

The example works perfectly fine for me though

**Comment by sanny-io** [comment]
Thank you @HayHay404 

I would guess this is related to the imports in the Next.js service. I had thought that they would be fine because they're only type imports, but that may not be the case. I will look into it this weekend and get back to you, hopefully with a fix.

**Comment by sanny-io** [comment]
@max-programming @HayHay404 please try react-appwrite 0.4.2 and let me know if you are still experiencing this issue. Forgive me if it doesn't, I've replicated the error, but it went away and I'm having a hard time trying to get it to appear again even after reverting my changes.

**Comment by max-programming** [comment]
Sure! I'll try and let you know

**Comment by sanny-io** [comment]
Thank you. Please also try placing the below in your Next.js configuration. This issue may be relevant vercel/next.js/issues/39375

`transpilePackages: ['react-appwrite']`
