### ISSUE TITLE
Total

### ISSUE THREAD

**Issue by dishwasher-detergent** [react-appwrite/react-appwrite#44]
In the useCollection hook, I think it would nice to have the ability to not only get the documents returned but also the total. I was wanting to use the total when making a pagination component. Could we return the whole the whole [document list object](https://appwrite.io/docs/models/documentList)?

**Comment by sanny-io** [comment]
Good catch! Will add this.

**Comment by sanny-io** [comment]
Actually, from the description, it sounds like it's essentially just returning the length of the documents array. Am I understanding that right, @dishwasher-detergent ?

**Comment by dishwasher-detergent** [comment]
From my experience, the total does not take the limit into count. It will return the number of every item that could made your where condition.

**Comment by sanny-io** [comment]
By taking the limit into account, I mean if there are 5 total documents, and your query is `SELECT abc FROM xyz LIMIT 3`, the total still says 5, even though there are only 3 documents returned.

**Comment by dishwasher-detergent** [comment]
Ohhh, yea you're right.

**Comment by sanny-io** [comment]
To be released this weekend.
